### ISSUE TITLE
Async/Await Support

### ISSUE THREAD

**Issue by BenjaminGibbs** [chargebee/chargebee-dotnet#11]
Are there any plans on the road map for Async/Await support on the http requests?

**Comment by kogir** [comment]
@BenjaminGibbs I hacked something together over at https://github.com/realartists/chargebee-dotnet Be sure to test the paths you use pretty thoroughly though. It's rough right now.

**Comment by 1TheMuffinMan** [comment]
I am also interested in async support.

**Comment by christianscheuer** [comment]
Fwiw, I've implemented async/await support here in my branch, which is based off of dexgrid's branch that support .NET core:
https://github.com/christianscheuer/chargebee-dotnet

**Comment by Thanaen** [comment]
That would be a really helpful feature, as ChargeBee's API calls can be really long sometimes! Sadly, it looks like they aren't really aware of github's issues

**Comment by cb-rakesh** [comment]
This has been fixed since version 2.7.8.
