### ISSUE TITLE
NuGet.exe is not checked in

### ISSUE THREAD

**Issue by wallyuva** [chargebee/chargebee-dotnet#12]
When you clone the repo and attempt to rebuild for the first time, the NuGet package restore fails because it can't find NuGet.exe. Please check it into the repo to resolve this.  I am unsure what version of NuGet.exe you would like to use there, so i didn't create a pull request.

**Comment by WafaaNasr** [comment]
Hello Wallyuva :), Kindly help this's my first time to deal with repo, as i always use VS to manage Nuget through the VS's package manager console. and I couldn't get you when saying " Please check it into the repo to resolve this. "

thank you!

**Comment by tonydrake** [comment]
As NuGet.exe is excluded, it's not uploaded into the repo (in the .NuGet directory we don't see it, but it's needed). Easy to fix, by dropping the exe in the .NuGet directory though.

**Comment by cb-khushbubibay** [comment]
Hi @wallyuva,

Sorry for the late response.

To promote a cleaner development environment and to reduce repository size, we have not included nuget.exe file.
Requesting you to please use NuGet package as referred in Readme file, it provides the tools for creating, publishing, and consuming packages.
It maintains a reference list of packages used in a project and the ability to restore and update those packages from that list.

Hope this helps you understand better. Closing this issue.
