### ISSUE TITLE
ArgumentException when trying to set Limit or Offset in list request

### ISSUE THREAD

**Issue by luciobemquerer** [chargebee/chargebee-dotnet#13]
Hello guys, We are getting ArgumentException when trying to set Limit or Offset of ListRequestBase<T>. 

We are using the same request multiple times to be able to download lists with more than 100 entries. This exception is really annoying, because the ListRequestBase object does not make it clear that we are working with a dictionary, and does not allow us to see or change existing values.

I wonder if this behavior is intended, and if it is, why.

For now we are having to resource to workarounds to recreate requests every time, which is very annoying.

**Comment by nils-czernig** [comment]
I have the same problem.. is there a workaround for that problem?

**Comment by SangeethaBaskaran** [comment]
Hi @luciobemquerer @nils-czernig, we have fixed this in the commit 25d0aca9eefb9a1816846b28f03a06facf24c0b7. Closing this issue.
