### ISSUE TITLE
MetaData is not available on subscription

### ISSUE THREAD

**Issue by dampee** [chargebee/chargebee-dotnet#16]
There is no way to access the meta data stored on a subscription after you do a

    var subscription = ChargeBee.Models.Subscription.Retrieve(subscriptionId).Request();

Could this be added?

Kind regards

**Comment by cb-khushbubibay** [comment]
Hi @dampee 
We added MetaData field in v1.6.0.
you can access metadata with GetJToken function as below.

subscription.GetJToken("meta_data");
OR
subscription.MetaData

Please reopen if you are not able to access it in this way or have other questions.
