### ISSUE TITLE
PortalSession not accepting ':' character to specify port for redirect parameter

### ISSUE THREAD

**Issue by sanjaygovindan** [chargebee/chargebee-dotnet#23]
All other redirect parameters for entities such as HostedPages accept ':' character to specify a port.
However the PortalSession entity doesn't support specifying a port using this character. 

`var portal = ChargeBee.Models.PortalSession.Create()
                    .CustomerId(chargebeeCustomerId)
                    .RedirectUrl("https://localhost:4444/test")
                    .Request();
`

**Comment by cb-sriramthiagarajan** [comment]
Hi @sanjaygovindan, I'm sorry for the delay in response. We currently support only these port numbers for redirect URL — `443`, `80`, `8443`, `8080`. The same can also be seen in the API error message now:

```json
{
    "message": "redirect_url :  Only [443, 80, 8443, 8080] ports are allowed",
    "type": "invalid_request",
    "api_error_code": "invalid_request",
    "param": "redirect_url",
    "error_code": "UNSUPPORTED_PORT",
    "error_msg": " Only [443, 80, 8443, 8080] ports are allowed",
    "error_param": "redirect_url",
    "http_status_code": 400
} 
```

I hope this clarifies. Please feel free to reopen this issue or create a new one if you have any further questions. Thanks.
