### ISSUE TITLE
Currency Issue

### ISSUE THREAD

**Issue by ajayak** [chargebee/chargebee-dotnet#24]
From currency docs, https://apidocs.chargebee.com/docs/api#currencies
It says Chargebee uses the smallest unit in the currency.

#Issue:
Create an order with order total 100 USD.
In the event, the `CurrencyCode` is USD and `Total` is 10000 which is absolutely wrong.

Instead of handling the conversion in our app, it should be handled in SDK or chargebee itself

**Comment by rowandh** [comment]
If the smallest unit in the currency is 1c, this seems correct. Or am I misunderstanding?

**Comment by ajayak** [comment]
Hi @rowandh , if the currency is Cents, the `CurrencyCode` should not have *USD*

**Comment by cb-khushbubibay** [comment]
> It says Chargebee uses the smallest unit in the currency.

Thanks for alerting us. We have updated the docs since then and stated clearly that the currency values are actually N X 100 where N is the value in major units of the currency.
Requesting you to please refer the latest version of doc: https://apidocs.chargebee.com/docs/api#currencies
