### ISSUE TITLE
Data loss serializing Estimate

### ISSUE THREAD

**Issue by jamespjones** [chargebee/chargebee-dotnet#28]
Hi

I found InvoiceEstimateTax and the other InvoiceEstimate subclass objects don't serialize as one would expect. I think it's due to the objects having methods rather than properties for things like Name, Description and Amount...  

I ran into this trying to return an estimate in a webservice response (where serialization to JSON is done automatically) but easier example code to see the issue is:

```c#
EntityResult result = Estimate.CreateSubscription()
        .SubscriptionPlanId("<plan-id>")
        .SubscriptionPlanQuantity(1)
        .BillingAddressCountry("<country-code>")
        .Request();

var estimate = result.Estimate;
Console.WriteLine($"Taxes Count (before serialization): {estimate.InvoiceEstimate.Taxes?.Count}");

var json = Newtonsoft.Json.JsonConvert.SerializeObject(estimate);
Console.WriteLine($"JSON: {json}"); // Tax data missing
```

**Comment by cb-khushbubibay** [comment]
This issue has been fixed in v2.14.0. Hence closing this issue.
