### ISSUE TITLE
2.8.4 is not compatible with net48

### ISSUE THREAD

**Issue by nicholastic** [chargebee/chargebee-dotnet#29]
Error message, also tested with a new project:

Package chargebee 2.8.4 is not compatible with net48 (.NETFramework,Version=v4.8). Package chargebee 2.8.4 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)

Also:

Could not install package 'chargebee 2.8.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by cb-khushbubibay** [comment]
Hi @nicholastic 
Sorry for the late response. 
You got these error because the support for version net48 is added from chargebee 2.8.5.
Requesting you to please upgrade the chargeebee package.
Please raise new issue if you have any further query.
