### ISSUE TITLE
Subscription instances do not survive a serialize/deserialize cycle (v2.8.0)

### ISSUE THREAD

**Issue by pollax** [chargebee/chargebee-dotnet#31]
Instances of the Subscription class cannot be deserialized. When retrieving the Subscription.CustomerId property after deserialization it fails with a `NullReferenceException`.

````
var subsText = Newtonsoft.Json.JsonConvert.SerializeObject(result.Subscription);

// writes out a json as expected, including the Subscription.CustomerId property
Console.WriteLine(subsText); 

var subs = Newtonsoft.Json.JsonConvert.DeserializeObject<Subscription>(subsText);

// Throws a NullReferenceException when trying to access the CustomerId property
Console.WriteLine(subs.CustomerId); 
````

**Comment by tgiachi** [comment]
Any update of this?

**Comment by cb-khushbubibay** [comment]
Hi @pollax and @tgiachi 

The newtonsoft serialisation/deserialisation function is not fully functional with chargebee-dotnet package.
Requesting you to please use below utilities method introduced in v2.16.0.

To serialise an object:
**ApiConfig.SerialiseObject(obj);**

To Deserialise an object:
**ApiConfig.DeserialiseObject<T>(jsonString);**
