### ISSUE TITLE
CheckoutOnetime

### ISSUE THREAD

**Issue by nilzzzzzz** [chargebee/chargebee-dotnet#32]
Hi,

in you api docs i can see the CheckoutOneTime function on the hosted page class: https://apidocs.chargebee.com/docs/api/hosted_pages?prod_cat_ver=1&lang=dotnet#checkout_one-time_payments

This seems not to be available through this library, can update this please?

Thanks!

**Comment by cb-rakesh** [comment]
This has been fixed in v2.8.9
