### ISSUE TITLE
Multi tenant support

### ISSUE THREAD

**Issue by oscarvantol** [chargebee/chargebee-dotnet#34]
At a client we need to connect with multiple ChargeBee entities from one application context.  With the current static implementation of ApiConfig it seems quite impossible. But the documentation site says this:
![image](https://user-images.githubusercontent.com/17926915/110494959-59afc880-80f4-11eb-8c0a-c7160e0e2a60.png)

There is a way of passing an ApiConfig instance along with the request and that would solve it... But the ApiConfig does not have a public constructor nor can I inherit it because it is sealed.

**Is there a recommended way to do this?** If not, would you consider changes I would suggest in a PR?

**Comment by oscarvantol** [comment]
Created a PR for this issue.

**Comment by jensweigele** [comment]
I also have the requirement for multi tenant support and with the current API this is only possible with some workarounds.
Before building each request you need to enter a mutex/semaphore, set the global config and generate the request.
The mutex is necessary to avoid race conditions if multiple threads are communication with chargebee.

I would appreciate if somebody could review the PR and merge it!

**Comment by jensweigele** [comment]
Thanks - I'll have a look at that!

**Comment by cb-rakesh** [comment]
This has been fixed in v2.10.0
