### ISSUE TITLE
Subscription update request with '#' as part of the id fails 

### ISSUE THREAD

**Issue by stnoa** [chargebee/chargebee-dotnet#39]
Subscription update requests with '#' as part of the id fail with a seemingly unrelated exception.

The error is part of the Chargebee api. The following request will return an error:

Request:
```curl https://*.chargebee.com/api/v2/subscriptions/#test1234 -u *: -d cf_field="value"```

Response:
```{"message":"plan_id : cannot be blank","type":"invalid_request","api_error_code":"invalid_request","param":"plan_id","error_code":"param_required","error_msg":"cannot be blank","error_param":"plan_id","http_status_code":400}```

The id has to be url encoded. The following request works:
```curl https://*.chargebee.com/api/v2/subscriptions/%23test1234 -u *: -d cf_field="value"```

Since the sdk already uses ```Uri.EscapeDataString```, there is currently no way to make this call work. Most likely ```Uri.EscapeDataString``` should be used instead.

This could be an issue with all requests that have the id as path parameter.

**Comment by cb-khushbubibay** [comment]
This issue has been fixed in v2.14.0. Hence closing this issue.
