### ISSUE TITLE
Serialization of Models.Subscriptions fails with Product Catalog 2.0 (The property plan_id is not present!)

### ISSUE THREAD

**Issue by mattias-skold** [chargebee/chargebee-dotnet#40]
Steps to repro ... 
Add a JsonConvert.SerializeObject(result); to the demo code on https://apidocs.chargebee.com/docs/api/subscriptions?prod_cat_ver=2#create_subscription_for_items 

EntityResult result = Subscription.CreateWithItems("__test__8asz8Ru9WhHOJO")
		.SubscriptionItemItemPriceId(0,"basic-USD")
		.SubscriptionItemBillingCycles(0,2)
		.SubscriptionItemQuantity(0,1)
		.SubscriptionItemItemPriceId(1,"day-pass-USD")
		.SubscriptionItemUnitPrice(1,100)
		.Request();

var thisWillFail = JsonConvert.SerializeObject(result);

**Comment by cb-yateshmathuria** [comment]
@mattias-skold - there is a method GetJToken() you can use to get the serialized object. Below is the code snippet.

EntityResult result = Subscription.CreateWithItems("__test__8asz8Ru9WhHOJO")
.SubscriptionItemItemPriceId(0,"basic-USD")
.SubscriptionItemBillingCycles(0,2)
.SubscriptionItemQuantity(0,1)
.SubscriptionItemItemPriceId(1,"day-pass-USD")
.SubscriptionItemUnitPrice(1,100)
.Request();

String serializedObject = result.Subscription.GetJToken().ToString()

Currently working on building support for JsonConvert.SerializeObject

**Comment by chrisperish** [comment]
The same issue occurs on deserialization of Subscriptions.  If I retrieve an event via the SDK then read the subscription within the contents of the event object it throws an error stating that there is no Plan_Id.

**Comment by cb-khushbubibay** [comment]
Hi All,
Thanks for raising this concern.
This issue has been fixed in v2.19.0 version, requesting you all to please update the package and tried once.
