### ISSUE TITLE
Obsolete ApiException property does not have property that obsoletes it

### ISSUE THREAD

**Issue by bizunas** [chargebee/chargebee-dotnet#41]
https://github.com/chargebee/chargebee-dotnet/blob/afd9f77e9e2cbb819b7e0ef529b71e6eb65341e2/ChargeBee/Api/ApiException.cs#L51

There is no `Code` in ApiException. Either remove `Obsolete` attribute or create the property for it to be properly used

**Comment by cb-khushbubibay** [comment]
Hi @bizunas,
This issue has been fixed in v2.16.0. Hence closing this issue.
