### ISSUE TITLE
customFields in customer Retrieve

### ISSUE THREAD

**Issue by tgiachi** [chargebee/chargebee-dotnet#46]
Is possibile get customFields for customer? I don't see the property 

thank you

**Comment by cb-yateshmathuria** [comment]
Hi @tgiachi - you can access custom fields with `GetValue<T>` as below (where `gender` is a custom field as `string` type).


`customer.GetValue<string>("cf_gender");`

Please reopen if you are not able to access it in this way or have other questions.

**Comment by tgiachi** [comment]
Thank you!
