### ISSUE TITLE
Add product_catalog_version call

### ISSUE THREAD

**Issue by wsypooh** [chargebee/chargebee-dotnet#47]
It is suggested that we check the product_catalog_version of the account so we can have our code support both versions during migration. Please add.

https://docs.google.com/document/d/1fBWdStVjk8BW_FuBmnYfYfm6vuMgKqQafrmm1jxmUoo/edit

**Comment by cb-khushbubibay** [comment]
Hi @wsypooh 
Sorry for the inconvenience. This API is hidden as of now, as it is under review process.
