### ISSUE TITLE
Support for feature-management

### ISSUE THREAD

**Issue by tgiachi** [chargebee/chargebee-dotnet#48]
Is possible to call api of feature-management and subscription_entitlements ?

ref:
https://apidocs.chargebee.com/docs/api/subscription_entitlements

thank you!

**Comment by cb-khushbubibay** [comment]
Hi @tgiachi 
Our new Entitlements feature is currently in the Early Adopter Program. For release notes and access to the feature, please write to us at [eap@chargebee.com](mailto:eap@chargebee.com).
