### ISSUE TITLE
How do I create Usage?

### ISSUE THREAD

**Issue by gjvdkamp** [chargebee/chargebee-dotnet#50]
Hi, 

I want to send usage data from our app back to Chargebee but I'm missing two things: 
What I have now is this: 

```
long UnixNow() { return (long)(DateTime.Now - new DateTime(1970, 1, 1)).TotalSeconds; }
ApiConfig.Configure("mysite-test", "myApiKey");

var u = Usage.Create("usageGuid").UsageDate(UnixNow()).ItemPriceId("Addon-Key").Quantity("5");
u.Request();

```

How do I set the subscriptionId that I want to post usage for? A fluent function for subscription_id doesn't seem to exist on CreateRequest? https://github.com/chargebee/chargebee-dotnet/blob/master/ChargeBee/Models/Usage.cs

**Comment by gjvdkamp** [comment]
ok solved the date issue 2)
long UnixNow() { return (long)(DateTime.Now - new DateTime(1970, 1, 1)).TotalSeconds; }

**Comment by cb-khushbubibay** [comment]
Hi @gjvdkamp 
Please try below sample code to create usage.

>  EntityResult result = Usage.Create("**Subscription_ID**")
                .ItemPriceId("sss-USD-Daily")//sss-USD-Daily
                .UsageDate(1677150875)
                .Note("Day 1 usage from __test__XpbBrciSCKqKUcN")
                .Quantity("5")
                .Request();
            Usage usage = result.Usage; 
            Console.WriteLine(ApiConfig.SerializeObject(usage));

Please let us know if this works for you.
Awaiting your response.
