### ISSUE TITLE
Missing Layout method on Hosted Page

### ISSUE THREAD

**Issue by peterjgrainger** [chargebee/chargebee-dotnet#52]
According to the API docs there is a method named `Layout` https://apidocs.chargebee.com/docs/api/hosted_pages?prod_cat_ver=2&lang=dotnet#checkout_charge_items_and_one_time_charges_layout

Using the SDK there doesn't seem to be this method and I can't find it in the code.

**Comment by cb-khushbubibay** [comment]
Hi @peterjgrainger 
Thanks for raising this concern.
We have kept these attribute under our EAP feature.
Request you to please follow the info given for this attribute and contact eap@chargebee.com to enable this feature.

**Full Page Checkout is in early access. Contact eap@chargebee.com to enable this feature.**

**Comment by peterjgrainger** [comment]
Thanks for the quick reply! I'll ask our implementation consultant :)

**Comment by peterjgrainger** [comment]
@cb-khushbubibay - is this a missing parameter or is it hard coded or defaulted to inapp?

**Comment by cb-dinesh** [comment]
@peterjgrainger The `Layout` parameter is an early access feature, this parameter enables one to set the Checkout's layout at runtime between `full_page` or `in_app`. However, the default layout is set as `in_app`. 

So in your case, you don't have to pass any value to the `Layout` parameter
