### ISSUE TITLE
ChargeBee.Models.Subscription.UpdateForItemsRequest in EntityResult throws 

### ISSUE THREAD

**Issue by mattias-skold** [chargebee/chargebee-dotnet#56]
Consider this code 
ChargeBee.Models.Subscription.UpdateForItemsRequest subReq = ChargeBee.Models.Subscription.UpdateForItems(subscriptionId.ToString())
                          .SubscriptionItemItemPriceId(0,planId)
                          .SubscriptionItemQuantity(0, planQuantity);
EntityResult result = subReq.Request();

After the call - any access to result.Subscription thows the exception below. 

Error getting value from 'Index' on 'ChargeBee.Models.Subscription+SubscriptionItemTier'. ChargeBee: The property index is not present!.

**Comment by cb-khushbubibay** [comment]
Hi @mattias-skold 
I used the below code snippet to reproduce the issue.

```
ApiConfig.Configure("test-site","API-Key");

ChargeBee.Models.Subscription.UpdateForItemsRequest result1 = Subscription.UpdateForItems("16CJApTNQi4MhCVz")
   .SubscriptionItemItemPriceId(0,"cbdemo_basic-USD-monthly")
   .SubscriptionItemQuantity(0,4)
   .SubscriptionItemUnitPrice(0,1000)
   .InvoiceImmediately(true);

EntityResult result = result1.Request();

Subscription subscription = result.Subscription;
Console.WriteLine(subscription.Coupons);  
Customer customer = result.Customer;
Card card = result.Card;
Invoice invoice = result.Invoice;
List<UnbilledCharge> unbilledCharges = result.UnbilledCharges;
List<CreditNote> creditNotes = result.CreditNotes;
Console.WriteLine(subscription); 
```

The above code snippet works fine, Please try to use the same.
In case of any further issue please feel free to reach us.
