### ISSUE TITLE
Subscription API error with tiered pricing

### ISSUE THREAD

**Issue by chalber** [chargebee/chargebee-dotnet#57]
Hi,

We're getting an error when querying for a list of subscriptions by account Id, from the debugger stack trace it looks like Chargebee is not returning the index key for tiered pricing, all our subscriptions are tiered pricing.

**SDK:** chargebee.net v3.0.0, also tested on v2.22.0

**Error Message:** 
```
Newtonsoft.Json.JsonSerializationException: Error getting value from 'Index' on 'ChargeBee.Models.Subscription+SubscriptionItemTier'.
       ---> System.ArgumentException: The property index is not present!
```
**Debugger screenshot:**
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/13370804/208784808-b1cff9ae-a80f-4a27-83d5-3e6d6f4076c9.png">

**Code:**
```c#
  var subscriptions = await Subscription.List()
                .CustomerId()
                .Is(accountId)
                .RequestAsync();
```

**Comment by cb-khushbubibay** [comment]
Hi @chalber 

Could you please try below code snippet.
```
var subscriptions = await Subscription.List()
    .CustomerId()
    .Is("5buVKh8VGmHkpiBMElhL")
    .RequestAsync();
foreach (var item in subscriptions.List){
    Subscription subscription = item.Subscription;
    Console.WriteLine(ApiConfig.SerializeObject(subscription));
    Customer customer = item.Customer;
    Card card = item.Card;
}
```

You can also check API doc code snippet sample to get the object lists: [Subscriptions | .Net Client Library  | Chargebee API documentation](https://apidocs.chargebee.com/docs/api/subscriptions?prod_cat_ver=2&lang=dotnet#list_subscriptions)

**Comment by cb-khushbubibay** [comment]
Hi @chalber
Hope your issue is resolved now.
Closing this issue, please raise a new Issue/PR in case of any further query.
