### ISSUE TITLE
Setting a single value of the BillingInfo not possible

### ISSUE THREAD

**Issue by cyrilmestrom** [chargebee/chargebee-dotnet#58]
When trying to update a single property of the BillingInfo object I have to fill the complete object otherwise it will clear all the other properties in the Customer.
A workaround would be to retrieve the customer and prefill the object and then add the changed values, but becuase it is a Dictionary I will get the  _An item with the same key has already been added._  exception. I think it would be nicer if setting a param would just override the currently set value.

**Comment by cb-khushbubibay** [comment]
Hi @cyrilmestrom 
The update functionality expects all the added existing fields as well,  if those are provided the update should work.
Regarding **An item with the same key has already been added** exception, I guess you are trying to update the same field twice in single update request. 
For instance , in below sample code BillingAddressLine1 field is added twice so this will throw excaption.
> EntityResult result = Customer.UpdateBillingInfo("169lgbTPtQVvdsGvv3")
                 .BillingAddressFirstName("John")
                 .BillingAddressLastName("Doe")
                 .BillingAddressLine1("PO Box 9999")
                 .BillingAddressCity("Walnut")
                 .BillingAddressState("California")
                .BillingAddressLine1("PO Box 9999")//Adding same line again will give exception (System.ArgumentException: An item with the same key has already been added. Key: billing_address[line1])
                 .BillingAddressZip("91789")
                 .BillingAddressCountry("US")
                 .Request();
                Customer customer = result.Customer;

**Comment by cyrilmestrom** [comment]
Thanks cb-khushbubibay! I understand the reason why it throws, it would just be easier implementing if it wouldn't, because as the API doesn't allow the update of a single property, I could then just retrieve the billingInfo object, fill all the properties by default and then update whatever property is changed in my event handler. Now I need to check every property, if I should prefill it.
