### ISSUE TITLE
Multiple chargebee account from single application

### ISSUE THREAD

**Issue by puneetpathak1979** [chargebee/chargebee-dotnet#6]
I have 2 chargebee account let say A and B, i want some of my user to subscribe in account A and others in account B.

I am using Hosted pages to redirect user to chargebee subscription page.

I initialize api keys every time before i send request on chargebee.

Now suppose if a user comes and he will be subscribing to account A, i will get the URL of hosted page & i will redirect him on subscription page.

Another user comes (on different system, different place) and subscribe to account B, I m not getting URL of hosted page for the first time, if i send the request again i will get the URL. Now it will work fine until some one goes to subscribe in account A.

And now the user who is paying in account A will face the same problem for the first time.

**Comment by cb-raghu** [comment]
Could you send us the sample code that you use to initialize the site name, API key and the hosted page API call for both the accounts ?

**Comment by puneetpathak1979** [comment]
Sorry for the delay raghu, below is the sample code




Shared Sub setApiKeysByGatewayMode(ByVal apiKeyType As Integer)        
            ''Keys and site name are not real
            If apiKeyType = 1 Then
                ApiConfig.Configure("xyz", "kaoe9msmcjds09qmjqjqjc8292222")
            ElseIf apiKeyType = 2 Then
                ApiConfig.Configure("abc", "pospsikIISM912029829kdckdkdkk")            
            End If
End Sub

Public Shared Function GetHostedPageUrl()
         Dim hostedPageRequest = HostedPage.CheckoutNew()

         hostedPageRequest.CustomerId(customerId)
         hostedPageRequest.SubscriptionPlanId(planId)
         ...........................................................................
         ...........................................................................
         ...........................................................................
         setApiKeys(apiKeyType)

         Dim hostedPageResult As EntityResult = hostedPageRequest.Request()


         result = hostedPageResult.HostedPage.Url
          
End Sub

**Comment by cb-raghu** [comment]
Hi 
Your code seems to look fine. We would want to confirm that your site name and api key is set properly before calling our api.

Please add the below statement in your existing code before calling our API and ensure that the correct site name is set in the ApiConfig,

ApiConfig conf = ApiConfig.Instance;
Console.WriteLine(conf.SiteName);


However here is the alternate way to call our API if you have multiple sites. 

ApiConfig.Configure ("xyz", "test_fhggh");
ApiConfig conf1 =  ApiConfig.Instance;

ApiConfig.Configure ("abc", "test_dfdggffgf");
ApiConfig conf2 =  ApiConfig.Instance;

ApiConfig conf;

setApiKeysByGatewayMode(1);
GetHostedPageUrl(conf);

setApiKeysByGatewayMode(2);
GetHostedPageUrl(conf);




Shared Sub setApiKeysByGatewayMode(ByVal apiKeyType As Integer)

If apiKeyType = 1 Then
conf = conf1;
ElseIf apiKeyType = 2 Then
conf = conf2;

End If
End Sub


// pass the api config object 
Public Shared Function GetHostedPageUrl(ByVal conf As ApiConfig)
Dim hostedPageRequest = HostedPage.CheckoutNew()

     hostedPageRequest.CustomerId(customerId)
     hostedPageRequest.SubscriptionPlanId(planId)
   
   // sending the request with the selected conf object
     Dim hostedPageResult As EntityResult = hostedPageRequest.Request(conf)


     result = hostedPageResult.HostedPage.Url
End Sub

**Comment by puneetpathak1979** [comment]
Hi Raghu,
I checked the api keys before asking for help from you, I logged them in file after initializing and before sending request on your server.

I am trying alternative you have suggested, I will let you know if it is working or not.

**Comment by puneetpathak1979** [comment]
Hi Raghu, 
I tried the alternative you suggested, but with no success.

Dim config = setApiKeys(apiKeyType)   ''// function returns ApiConfig.Instance depending on apiKeyType

Dim hostedPageResult As EntityResult = hostedPageRequest.Request(conf)

I passed ApiConfig.Instance object with request and also checked the keys (config.ApiKey,  config.SiteName) before sending request.

**Comment by cb-raghu** [comment]
Hi,
I am sharing my sample C# code below that simulates your use case. I have tested it at my end and it works fine.
Request you to modify the sample code with your details(api keys,site name and SubscriptionPlanId) and let us know if that solved your problem.

 The output log of the below sample code will print your configured site name and the hosted page url. Check if your hosted page url has the same site name for the corresponding api calls.

using System;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Net;
using System.Web;
using System.Reflection;

using ChargeBee.Api;
using ChargeBee.Models;
using ChargeBee.Models.Enums;

using Newtonsoft.Json;

namespace Examples
{

	public class Sample
	{
		// this method configures your account
		public static ApiConfig getApiConfig(int accountType){
			if (accountType % 2 == 0) {
				ApiConfig.Configure ("site-1", "Api-key-1");  // replace this with your site1 deails
				return ApiConfig.Instance;
			} else {
				ApiConfig.Configure ("site-2", "Api-key-2");    // replace this with your site2 deails
				return ApiConfig.Instance;
			} 
		}


		//this method calls your api method using the configured config object
		public static void callHostedPageApi(ApiConfig conf){
			HostedPage hostedPage;
			EntityResult result = HostedPage.CheckoutNew ()
				.SubscriptionPlanId ("enterprise_half_yearly") // replace this with your plan id
				.Request (conf);
			hostedPage = result.HostedPage;
			Console.WriteLine("URL : " + hostedPage.Url);
			Console.WriteLine ("-----------------------------------");
		}

		public static void Main(string[] args)
		{
			ApiConfig conf;
			int count = 0;
			do {
				if (count > 5) {
					break;
				}

				conf = getApiConfig (count); // configuring your account here
				Console.WriteLine ("Site Name : " + conf.SiteName); // verify your config object by printing your site name
				callHostedPageApi (conf); // call api using the above configuration
				count++;

			} while(true);
			Console.Write ("exit");
		}
	}
}

**Comment by puneetpathak1979** [comment]
Hi Raghu, 
The code you have given above has been already suggested by you in your previous reply. 
I have already tried this code and its not working for me.

**Comment by cb-raghu** [comment]
Hi,
As none of the above solutions worked for you we have written a VB method specific to your use case. This method would retrieve the hosted page url for the given site and plan id. We have tested this method at our end and it works fine. Hope this would solve your problem.
If you are still facing issues you can raise a ticket at support@chargebee.com mentioning your site id,complete sample code and the debugger statements of the below sample code.


// below is the code snippet that need to included in your file.

Public Shared configLock As New Object()

Public Shared Function getHostedPageUrl(siteName As [String], apiKey As [String], planId As [String]) As [String]
	SyncLock configLock
		ApiConfig.Configure(siteName, apiKey)
		Dim config As ApiConfig = ApiConfig.Instance

		Dim result As EntityResult = HostedPage.CheckoutNew().SubscriptionPlanId(planId).Request(config)

		Dim hostedPage__1 As HostedPage = result.HostedPage

		Return hostedPage__1.Url
	End SyncLock
End Function

/*--------------------------------------------------------------------------------------------*/

Here is an example of how to use the getHostedPageUrl method


Public Class Sample

	Public Shared configLock As New Object()

	Public Shared Function getHostedPageUrl(siteName As [String], apiKey As [String], planId As [String]) As [String]
		SyncLock configLock
			ApiConfig.Configure(siteName, apiKey)
			Dim config As ApiConfig = ApiConfig.Instance

			Console.WriteLine("Before API call : " + config.SiteName)

			Dim result As EntityResult = HostedPage.CheckoutNew().SubscriptionPlanId(planId).Request(config)

			Console.WriteLine("After API call : " + config.SiteName)

			Dim hostedPage__1 As HostedPage = result.HostedPage

			Console.WriteLine("url : " + hostedPage__1.Url)
			Console.WriteLine("------------------------------------------------")
			Return hostedPage__1.Url
		End SyncLock
	End Function

	Public Shared Sub Main(args As String())
		Dim url As [String] = ""
		Dim count As Integer = 0

		Do
			If count > 5 Then
				Exit Do
			End If

			If count Mod 2 = 0 Then

				url = getHostedPageUrl("site-id1", "api-key1", "plan-id1")
			Else
				url = getHostedPageUrl("site-id2", "api-key2", "plan-id2")
			End If


			count += 1
		Loop While True
		Console.Write("exit")
	End Sub
End Class

**Comment by puneetpathak1979** [comment]
Hi raghu, 
Appreciate your help, I was busy with our new release so was not able to revert back, but my concern is still the same.

Before send the request on your server and after the request has been sent i have logged the API keys, their is no problem with the keys no matter how many times i switch between the two keys.

The problem is whenever i switch between them an error is returned from your server (API AUTHENTICATION FAILED) for the first time and after this code starts working fine till the point i again changes the key. 

I implemented your above code but the problem is the same.

**Comment by cb-raghu** [comment]
Hi Punnet,
We would like to dig deeper in the issue by analyzing our logs so I request you to raise a ticket at support@chargebee.com mentioning the following details.
1. Site name
2. Your complete sample code
3. Debugger statements
