### ISSUE TITLE
Missing .Embed() method in HostedPage.CheckoutNewForItems and HostedPage.CheckoutExistingForItems requests for Product Catalog 2.0

### ISSUE THREAD

**Issue by mtomberger** [chargebee/chargebee-dotnet#70]
### Description of the Bug

I tried to migrate a Application which uses the Chargebee .NET API to be compatible with Product Catalog 2.0. 
I replaced the API methods according to the [upgrade guide](https://apidocs.chargebee.com/docs/api/v1/upgrade?lang=dotnet), but it is not possible to set the `embed` flag to `true` after using the new methods. It looks like this method is missing from the new API flow.

### Steps to reproduce

1) Use the new API methods for Product Catalog 2.0 to create a HostedPage using `HostedPage.CheckoutExistingForItems()` or `HostedPage.CheckoutNewForItems()`
2) Try to set the embed flag to ture via the API

### Expected Behavior

The emped flag can be set to true with a .NET API Method within the `CheckoutNewForItemsRequest `and `CheckoutExistingForItemsRequest` classes

### Code Snippets (if applicable)

```csharp
var resultPC1 = HostedPage.CheckoutNew()
                                .CustomerEmail(m.CustomerMailAdress)
                                .SubscriptionPlanId("basic-USD")
                                .RedirectUrl(redirectUrl)
                                .Embed(false); //this method works as expected

var resultPC2 = HostedPage.CheckoutNewForItems()
                                .CustomerEmail(m.CustomerMailAdress)
                                .SubscriptionItemItemPriceId(0, "basic-USD")
                                .RedirectUrl(redirectUrl)
                                .Embed(false);//this method does not exist
```

### Operating System

Windows

### Language version

.NET 8

### Library version

3.18.1.0

**Comment by cb-alish** [comment]
Hi @mtomberger, `.Embed` is not supported in Product Catalog v2. Can you elaborate on your use case / what you're trying to achieve please?

**Comment by mtomberger** [comment]
I try to upgrade a application which uses `.Embed(false)` in various places. If omitting this call in Product Catalog 2.0 has the same effect as setting embed to false in Product Catalog 1.0 there is no problem.

**Comment by cb-alish** [comment]
Hi @mtomberger , the default behavior for the latest versions of checkout (in app and full page layout) is `Embed = false`. Please do let us know if you face any issues with this.

**Comment by cb-sriramthiagarajan** [comment]
Hi @mtomberger, I'm closing this issue as it's been addressed. Please feel free to reopen if you have any more questions.
